apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: java
  name: java-example
  labels:
    app: java-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-example
  template:
    metadata:
      labels:
        app: java-example
    spec:
      containers:
      - image: tkgregory/sample-metrics-application:latest
        imagePullPolicy: Always
        name: java-example
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: java
  name: java-example-service
  labels:                    
    app: java-example
spec:
  selector:
    app: java-example
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-example-service-monitor
  namespace: java
  labels:
    release: prometheus         
spec:
  selector:
    matchLabels:
      app: java-example
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s

